name = "llm-prices"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["0 */6 * * *"]

[assets]
directory = "./public"

[[rules]]
type = "Text"
globs = ["**/*.md"]
fallthrough = false

[[kv_namespaces]]
binding = "MODEL_PRICES"
id = "73eb710c056640bbb3e4e49968e51b22"
